name: Run kernel tests on all boards with custom SDK

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref (branch, tag, SHA, ...)'
        required: true
        default: 'main'
      sdkurl:
        description: 'Custom SDK URL'
        required: true
        default: 'http://builds.zephyrproject.org/zephyrproject-rtos/sdk-ng/000/zephyr-sdk-0.XX.X-pr-000-x86_64-linux-setup.run'

jobs:
  build:
    name: "${{ github.event.inputs.ref }} / Custom SDK (${{ matrix.subset }})"
    runs-on: [ self-hosted, linux, x64, large ]
    strategy:
      fail-fast: false
      matrix:
        subset: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

    env:
      MATRIX_SIZE: 10
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr

    steps:
      - name: Print run information
        run: |
          echo "ref    = ${{ github.event.inputs.ref }}"
          echo "sdkurl = ${{ github.event.inputs.sdkurl }}"

      - name: Print environment information
        run: |
          uname -a
          df -h
          cmake --version
          ls -l ${ZEPHYR_SDK_INSTALL_DIR}

      - name: Install custom SDK
        run: |
          rm -rf sdk
          mkdir sdk
          cd sdk
          wget --progress=dot:giga -O installer.run ${{ github.event.inputs.sdkurl }}
          chmod +x installer.run
          ./installer.run -- -d ${GITHUB_WORKSPACE}/sdk/sdkroot -y -norc -nocmake
          ls -l ./sdkroot

      - name: Set up west
        run: |
          pip3 install --user west
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          repository: Centrinix/zephyr
          ref: '${{ github.event.inputs.ref }}'
          path: zephyr

      - name: Check out modules
        run: |
          west init -l zephyr || true
          west update

      - name: Install Python dependencies
        run: |
          pip3 install --user -r zephyr/scripts/requirements.txt

      - name: Run tests with twister
        working-directory: zephyr
        run: |
          export ZEPHYR_SDK_INSTALL_DIR=${GITHUB_WORKSPACE}/sdk/sdkroot
          export ZEPHYR_BASE=${PWD}
          ./scripts/twister --inline-logs -M -N -v -T tests/kernel \
                            --subset ${{ matrix.subset }}/${MATRIX_SIZE} \
                            --retry-failed 3

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results (Subset ${{ matrix.subset }})
          path: zephyr/twister-out/twister.xml

      - name: Clean up
        if: always()
        run: |
          rm -rf sdk
          cd zephyr
          git clean -dxf
